name: Deploy Pipeline

on:
  push:
    branches:
      - prd
      - hom

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Login seguro no GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Setup QEMU para suporte multi-arquitetura
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and Push Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}:cache \
            --cache-to=type=inline \
            -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            --push .
